server:
  port: 8443
  ssl:
    key-store: D:\JavaProgram\ShoppingCart\src\main\resources\keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: tomcat
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/cart_db?serverTimezone=UTC
#    database for test
    url: jdbc:mysql://localhost:3306/cartTest_db?serverTimezone=UTC
    username: root
    password: 12345678
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
mybatis:
  type-aliases-package: com.idv.yen.mapper

#ngrok:
#  enabled: true
